<?php
try {
    throw new Exception("Something went wrong");
} catch (Exception $e) {
    echo "Caught exception: " . $e->getMessage();
}
?>
This uses a try-catch block to handle exceptions. If an exception is thrown, it gets caught and handled gracefully.